const registerUser = async () => {
  try {
  } catch (error) {
    console.log("Error in Registering User: ", error.message);
  }
};
const loginUser = async () => {
  try {
  } catch (error) {
    console.log("Error in Logging In User: ", error.message);
  }
};
const logoutUser = async () => {
  try {
  } catch (error) {
    console.log("Error in logging Out User: ", error.message);
  }
};
const getAllUsers = async () => {
  try {
  } catch (error) {
    console.log("Error in getting All Users: ", error.message);
  }
};
const getUserById = async () => {
  try {
  } catch (error) {
    console.log("Error in getting Single User: ", error.message);
  }
};
const updateUser = async () => {
  try {
  } catch (error) {
    console.log("Error in Updating User: ", error.message);
  }
};
const deleteUser = async () => {
  try {
  } catch (error) {
    console.log("Error in Deleting User: ", error.message);
  }
};

module.exports = {
  registerUser,
  loginUser,
  logoutUser,
  getAllUsers,
  getUserById,
  updateUser,
  deleteUser,
};
