const registerUser = async () => {
  try {
  } catch (error) {
    console.log("Error in Registering User: ", error.message);
  }
};
const loginUser = async () => {
  try {
  } catch (error) {
    console.log("Error in Logging In User: ", error.message);
  }
};
const logoutUser = async () => {
  try {
  } catch (error) {
    console.log("Error in logging Out User: ", error.message);
  }
};

export { registerUser, loginUser, logoutUser };
